version: '3.9'

services:

    node:
        image: node:latest
        ports:
            # - "80:80"
            - "3000:3000"
            - "5000:5000"
            - "443:443"
            - "35729:35729" #for hotreloading
        volumes: 
            # - ./sq-react/client:/usr/src/app
            - ./sq-react:/usr/src/app
        #   - .:/usr/src/app
        working_dir: /usr/src/app
        stdin_open: true
        tty: true
        environment: 
            - CHOKIDAR_USEPOLLING=true #requried for docker and VM
            # - DEBUG=express
            # - NODE_ENV=dev
        # command: tail -f /dev/null #container will not stop on begging
        # command: yarn start #bash
        command: yarn dev

    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8080:80
        environment:
                WORDPRESS_DB_HOST: db
                WORDPRESS_DB_USER: exampleuser
                WORDPRESS_DB_PASSWORD: examplepass
                WORDPRESS_DB_NAME: exampledb
        volumes:
                - wordpress:/var/www/html

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql

volumes:
    wordpress:
    db: